# Users should not change this file. This contains defaults for all build parameters. 
# If you want to change a build parameter, override the default by assigning it a value in ./build-parameters.toml


# Size of the per-core ring buffers used to stream events from eBPF to the daemon. 
# Note that is in terms of powers of 2. So 7 means that the ring buf size is (2^7) = 128
RING_BUF_SIZE_LOG2=7

