# Users should not change this file. This contains defaults for all build parameters.
# If you want to change a build parameter, set HTEK_BP_<param-name> to the desired value
# Ex) `export HTEK_HB_RING_BUF_SIZE_LOG2=20`
# Then run `make build`


# Size of the per-core ring buffers used to stream events from eBPF to the daemon.
# Note that is in terms of powers of 2. So 7 means that the ring buf size is (2^7) = 128
RING_BUF_SIZE_LOG2=19

# Relevant only to the daemon
# Enable asserts?
# Generally only used for develompent/debugging purposes
ASSERTS=false

# Relevant only to the daemon
# Enable performance tracking?
# Generally only used for develompent/debugging purposes
PERF_TRACKING=false

# Random number used to detect eBPF buffer overflow
# Only used when ASSERTS = true
# There's no reason you should need to change these
CANARY=872350975

NUM_CORES=32
